/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://etlm4gjnrvffndchjkf5oibqei.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zcb6s2djyngwxircnd2adnzrii",
    "aws_cognito_identity_pool_id": "us-west-2:7cfec17a-4c97-413c-a32a-680018d2e793",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_AdtTieFO4",
    "aws_user_pools_web_client_id": "7ejk13a5a4m38o2lvge3iek0eb",
    "oauth": {}
};


export default awsmobile;
