/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://etlm4gjnrvffndchjkf5oibqei.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zcb6s2djyngwxircnd2adnzrii",
    "aws_cognito_identity_pool_id": "us-west-2:4af0d7fd-a79e-4270-9e0b-360ad111e636",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_oaPUtigq0",
    "aws_user_pools_web_client_id": "628b000u7cjlkcq0s8uadgqg4r",
    "oauth": {}
};


export default awsmobile;
